arkypita/LaserGRBL

LaserGRBL/GrblFile.cs, LaserGRBL/LaserGRBL.csproj, LaserGRBL/RasterConverter/ImageProcessor.cs, LaserGRBL/RasterConverter/ImageTransform.cs, LaserGRBL/RasterConverter/RasterToLaserForm.Designer.cs, LaserGRBL/RasterConverter/RasterToLaserForm.cs, LaserGRBL/RasterConverter/RasterToLaserForm.resx
This release include
- Horizontal and Vertical image engraving
- Export generated GCODE
- Faster raster preview generation by parallel processing
and more
=> Horizontal and Vertical engraving

LaserGRBL/GrblCommand.cs, LaserGRBL/GrblFile.cs, LaserGRBL/SettingsForm.Designer.cs, LaserGRBL/SettingsForm.cs, LaserGRBL/SettingsForm.de.resx, LaserGRBL/SettingsForm.fr.resx, LaserGRBL/SettingsForm.it.resx, LaserGRBL/SettingsForm.resx
Add setting for laser mode, and update rendering paths to represent rapid moves as a non-cutting operation.
=> Setting to use LaserMode in GRBL 1.1

LaserGRBL/ComWrapper/Ethernet.cs, LaserGRBL/ComWrapper/IComWrapper.cs, LaserGRBL/ComWrapper/UsbSerial.cs, LaserGRBL/ConnectLogForm.Designer.cs, LaserGRBL/ConnectLogForm.cs, LaserGRBL/ConnectLogForm.it.resx, LaserGRBL/ConnectLogForm.resx, LaserGRBL/GrblCore.cs, LaserGRBL/LaserGRBL.csproj, LaserGRBL/MainForm.Designer.cs, LaserGRBL/MainForm.da.resx, LaserGRBL/MainForm.de.resx, LaserGRBL/MainForm.es.resx, LaserGRBL/MainForm.fr.resx, LaserGRBL/MainForm.it.resx, LaserGRBL/MainForm.pt-BR.resx, LaserGRBL/MainForm.resx, LaserGRBL/Properties/AssemblyInfo.cs, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.Designer.cs, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.resx, LaserGRBL/RasterConverter/ImageProcessor.cs, LaserGRBL/SettingsForm.Designer.cs, LaserGRBL/SettingsForm.cs, LaserGRBL/SettingsForm.resx
=> WiFi Ethernet

LaserGRBL/GrblFile.cs
Avoid iterate all starting points, just start from the first one.
=> Optimize the travel optimizer

LaserGRBL/AutoUpdate/NewVersionForm.fr.resx, LaserGRBL/ConnectLogForm.fr.resx, LaserGRBL/CustomButtonForm.fr.resx, LaserGRBL/GrblConfig.fr.resx, LaserGRBL/HotkeyManagerForm.fr.resx, LaserGRBL/IssueDetectorForm.fr.resx, LaserGRBL/LaserGRBL.csproj, LaserGRBL/MainForm.fr.resx, LaserGRBL/PreviewForm.fr.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.fr.resx, LaserGRBL/RasterConverter/RasterToLaserForm.fr.resx, LaserGRBL/ResumeJobForm.fr.resx, LaserGRBL/RunFromPositionForm.fr.resx, LaserGRBL/SettingsForm.fr.resx, LaserGRBL/Strings.fr.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.fr.resx
Hi,
I have finished the french traduction. But I can not test it : when I compile (In debug or Release), UI stay in english (I have test to change langage to DE, IT, HU but UI stay in English).
Regards,
=> Update french translation

LaserGRBL/GrblCore.cs, LaserGRBL/GrblFile.cs, LaserGRBL/RasterConverter/ImageProcessor.cs, LaserGRBL/SvgConverter/gcodeRelated.cs
All corrections for smoothieware :  
- Add Softreset
- remove softreset when open com port (Because soft reset close com port...)
- Add S value for first G1 send
- S values are defined between 0.0 and 1.1
=> Smootieware corrections v2

LaserGRBL/CustomButton.cs, LaserGRBL/CustomButtonForm.Designer.cs, LaserGRBL/CustomButtonForm.cs, LaserGRBL/CustomButtonForm.resx, LaserGRBL/PreviewForm.cs, LaserGRBL/UserControls/ImageButton.cs
1. Optional caption under image
- Length of text is limited by the width of the image
2. Reorder with visual effect
- Blue line where the new position will be
- mouse at first half of image = insert before, other half = insert after
3. Clickable URL in edit dialog
=> CustomButton Improvements

LaserGRBL/SettingsForm.resx, TRANSLATING.md
Updated TRANSLATING.md with a step-by-step tutorial on how to translate LaserGRBL.
=> Translation step-by-step

LaserGRBL/AutoUpdate/NewVersionForm.pl-PL.resx, LaserGRBL/ConnectLogForm.pl-PL.resx, LaserGRBL/CustomButtonForm.pl-PL.resx, LaserGRBL/GrblConfig.pl-PL.resx, LaserGRBL/HotkeyManagerForm.pl-PL.resx, LaserGRBL/IssueDetectorForm.pl-PL.resx, LaserGRBL/MainForm.pl-PL.resx, LaserGRBL/PreviewForm.pl-PL.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.pl-PL.resx, LaserGRBL/RasterConverter/RasterToLaserForm.pl-PL.resx, LaserGRBL/RasterConverter/ResolutionHelperForm.pl-PL.resx, LaserGRBL/ResumeJobForm.pl-PL.resx, LaserGRBL/RunFromPositionForm.pl-PL.resx, LaserGRBL/SaveOptionForm.pl-PL.resx, LaserGRBL/SettingsForm.pl-PL.resx, LaserGRBL/Strings.pl-PL.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.pl-PL.resx
LaserGRBL translation into Polish. Please enter the translation into the program.
=> LaserGRBL translation into Polish

LaserGRBL/AutoUpdate/NewVersionForm.pl-PL.resx, LaserGRBL/IssueDetectorForm.pl-PL.resx, LaserGRBL/PSHelper/PSEditorForm.pl-PL.resx, LaserGRBL/PSHelper/PSHelperForm.pl-PL.resx, LaserGRBL/PreviewForm.pl-PL.resx, LaserGRBL/RasterConverter/RasterToLaserForm.pl-PL.resx, LaserGRBL/RasterConverter/ResolutionHelperForm.pl-PL.resx, LaserGRBL/ResumeJobForm.pl-PL.resx, LaserGRBL/RunFromPositionForm.pl-PL.resx, LaserGRBL/SaveOptionForm.pl-PL.resx, LaserGRBL/SettingsForm.pl-PL.resx, LaserGRBL/Strings.pl-PL.resx
=> I updated LaserGRBL translation into Polish

LaserGRBL/AutoUpdate/NewVersionForm.de.resx, LaserGRBL/ConnectLogForm.de.resx, LaserGRBL/CustomButtonForm.de.resx, LaserGRBL/ExceptionManager.de.resx, LaserGRBL/GrblConfig.de.resx, LaserGRBL/HotkeyManagerForm.de.resx, LaserGRBL/IssueDetectorForm.de.resx, LaserGRBL/MainForm.de.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.de.resx, LaserGRBL/RasterConverter/RasterToLaserForm.de.resx, LaserGRBL/ResumeJobForm.de.resx, LaserGRBL/RunFromPositionForm.de.resx, LaserGRBL/SaveOptionForm.de.resx, LaserGRBL/SettingsForm.de.resx, LaserGRBL/Strings.de.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.de.resx
18 change files for german update transation
=> German Translation update

LaserGRBL/ConnectLogForm.zh-TW.resx, LaserGRBL/MainForm.zh-TW.resx, LaserGRBL/PSHelper/PSEditorForm.zh-TW.resx, LaserGRBL/PSHelper/PSHelperForm.zh-TW.resx, LaserGRBL/PreviewForm.zh-TW.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.zh-TW.resx, LaserGRBL/RasterConverter/RasterToLaserForm.zh-TW.resx, LaserGRBL/RasterConverter/ResolutionHelperForm.zh-TW.resx, LaserGRBL/SaveOptionForm.zh-TW.resx, LaserGRBL/SettingsForm.zh-TW.resx, LaserGRBL/StandardMaterials.zh-TW.psh, LaserGRBL/Strings.zh-TW.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.zh-TW.resx
We have updated and revised the Chinese meaning in version 3.6.
thank you for your help.
In addition, this version 3.6 "PreviewForm.zh-TW.resx" is also in English, can you help me check the reason?
-------------------------------
Strings.zh-TW.resx
And add unit description
Speed ​​>> (mm/min)
Step >> (mm)
Please help me check if the unit is correct, thank you
--------------------
In addition to this work, we found that you put other brands' information on ORTUR's brand. Can we cooperate? Or what are the conditions of cooperation
=> We have updated and revised the Chinese meaning in version 3.6.

LaserGRBL/GrblFile.cs
- Calculate travel distance for both start and end of a curve
- In case the ending is shorter, reverse the curve
- Remove Sqrt from distance calculation to speed up
=> Optimizer consider both ending of curves

LaserGRBL/AutoUpdate/NewVersionForm.tr-TR.resx, LaserGRBL/ConnectLogForm.tr-TR.resx, LaserGRBL/CustomButtonForm.tr-TR.resx, LaserGRBL/ExceptionManager.tr-TR.resx, LaserGRBL/GrblConfig.tr-TR.resx, LaserGRBL/HotkeyManagerForm.tr-TR.resx, LaserGRBL/IssueDetectorForm.tr-TR.resx, LaserGRBL/MainForm.tr-TR.resx, LaserGRBL/PSHelper/PSEditorForm.tr-TR.resx, LaserGRBL/PSHelper/PSHelperForm.tr-TR.resx, LaserGRBL/PreviewForm.tr-TR.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.tr-TR.resx, LaserGRBL/RasterConverter/RasterToLaserForm.tr-TR.resx, LaserGRBL/RasterConverter/ResolutionHelperForm.tr-TR.resx, LaserGRBL/ResumeJobForm.tr-TR.resx, LaserGRBL/RunFromPositionForm.tr-TR.resx, LaserGRBL/SaveOptionForm.tr-TR.resx, LaserGRBL/SettingsForm.tr-TR.resx, LaserGRBL/Strings.tr-TR.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.tr-TR.resx
I translated all the files you mentioned on Issues.
However, some files (examples are at the URL below) were not opened with the Resex program.
https://imgur.com/a/0YBY5yf
I also used "Resx resource programmer". I liked its interface and usability better.
=> Translating turkish language

LaserGRBL/CustomButtonForm.de.resx, LaserGRBL/ExceptionManager.de.resx, LaserGRBL/GrblConfig.de.resx, LaserGRBL/HotkeyManagerForm.de.resx, LaserGRBL/IssueDetectorForm.de.resx, LaserGRBL/LaserGRBL.csproj, LaserGRBL/LicenseForm.de.resx, LaserGRBL/MainForm.de.resx, LaserGRBL/PSHelper/PSEditorForm.de.resx, LaserGRBL/PSHelper/PSHelperForm.de.resx, LaserGRBL/PreviewForm.de.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.de.resx, LaserGRBL/RasterConverter/RasterToLaserForm.de.resx, LaserGRBL/RasterConverter/ResolutionHelperForm.de.resx, LaserGRBL/ResumeJobForm.de.resx, LaserGRBL/SaveOptionForm.de.resx, LaserGRBL/SettingsForm.de.resx, LaserGRBL/Strings.de.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.de.resx
Adds translations for new strings and resx files,
updates various translation strings,
removes translation strings where the source string no longer exists (is empty),
and makes some formatting/newlines consistent to the source strings (under the assumption they are optimized for product consistency and optimal display/layout).
This is a first iteration going through the translation.
=> Improve and extend German translation

LaserGRBL/MainForm.hu-HU.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.hu-HU.resx, LaserGRBL/RasterConverter/RasterToLaserForm.hu-HU.resx, LaserGRBL/SettingsForm.hu-HU.resx, LaserGRBL/Strings.hu-HU.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.hu-HU.resx
Updated Hungarian translation in:
MainForm
ConvertSizeAndOptionsForm for RasterConverter & SvgConverter
RasterToLaserForm
SettingsForm
Strings
=> Hungarian translation update

LaserGRBL/StateBuilder.cs
=> add R cmd when using g2g3

LaserGRBL/AutoUpdate/NewVersionForm.ro-RO.resx, LaserGRBL/ConnectLogForm.ro-RO.resx, LaserGRBL/CustomButtonForm.ro-RO.resx, LaserGRBL/ExceptionManager.ro-RO.resx, LaserGRBL/GrblConfig.ro-RO.resx, LaserGRBL/HotkeyManagerForm.ro-RO.resx, LaserGRBL/IssueDetectorForm.ro-RO.resx, LaserGRBL/LaserGRBL.csproj, LaserGRBL/LicenseForm.ro-RO.resx, LaserGRBL/MainForm.Designer.cs, LaserGRBL/MainForm.cs, LaserGRBL/MainForm.resx, LaserGRBL/MainForm.ro-RO.resx, LaserGRBL/PSHelper/PSEditorForm.ro-RO.resx, LaserGRBL/PSHelper/PSHelperForm.ro-RO.resx, LaserGRBL/PreviewForm.ro-RO.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.ro-RO.resx, LaserGRBL/RasterConverter/RasterToLaserForm.ro-RO.resx, LaserGRBL/RasterConverter/ResolutionHelperForm.ro-RO.resx, LaserGRBL/ResumeJobForm.ro-RO.resx, LaserGRBL/RunFromPositionForm.ro-RO.resx, LaserGRBL/SaveOptionForm.ro-RO.resx, LaserGRBL/SettingsForm.ro-RO.resx, LaserGRBL/Strings.ro-RO.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.ro-RO.resx, LaserGRBL/WiFiDiscovery/DiscoveryForm.ro-RO.resx
Support for ro_Ro language 03.01.2022. 
List of files added or updated are present below. Please review them and integrate them into main project if it's ok with you. Thank you!
Updated files:
-----------------------------------------------------------------
- LaserGRBL.csproj 
- MainForm.Designer.cs 
- MainForm.cs
- MainForm.resx
Added files:
-----------------------------------------------------------------
- ConnectLogForm.ro-RO.resx
- CustomButtonForm.ro-RO.resx
- ExceptionManager.ro-RO.resx
- GrblConfig.ro-RO.resx
- HotkeyManagerForm.ro-RO.resx
- IssueDetectorForm.ro-RO.resx
- LicenseForm.ro-RO.resx
- MainForm.ro-RO.resx
- PreviewForm.ro-RO.resx
- ResumeJobForm.ro-RO.resx
- RunFromPositionForm.ro-RO.resx
- SaveOptionForm.ro-RO.resx
- SettingsForm.ro-RO.resx
- Strings.ro-RO.resx
- …
=> support for RO language

LaserGRBL/ConnectLogForm.uk.resx, LaserGRBL/CustomButtonForm.uk.resx, LaserGRBL/ExceptionManager.uk.resx, LaserGRBL/GrblConfig.uk.resx, LaserGRBL/HotkeyManagerForm.uk.resx, LaserGRBL/IssueDetectorForm.uk.resx, LaserGRBL/LicenseForm.uk.resx, LaserGRBL/MainForm.uk.resx, LaserGRBL/PreviewForm.uk.resx, LaserGRBL/ResumeJobForm.uk.resx, LaserGRBL/RunFromPositionForm.uk.resx, LaserGRBL/SaveOptionForm.uk.resx, LaserGRBL/SettingsForm.uk.resx, LaserGRBL/Strings.uk.resx
Please accept my Ukrainian translation, which I made following your [documentation](https://github.com/arkypita/LaserGRBL/blob/master/TRANSLATING.md)
Almost 70% of strings are translated.
=> Ukrainian language

LaserGRBL/CustomButtonForm.pt-BR.resx, LaserGRBL/ExceptionManager.pt-BR.resx, LaserGRBL/GenerateForm.pt-BR.resx, LaserGRBL/GrblConfig.pt-BR.resx, LaserGRBL/HotkeyManagerForm.pt-BR.resx, LaserGRBL/IssueDetectorForm.pt-BR.resx, LaserGRBL/LegalDisclaimer.pt-BR.resx, LaserGRBL/LicenseForm.pt-BR.resx, LaserGRBL/MainForm.pt-BR.resx, LaserGRBL/PreviewForm.pt-BR.resx, LaserGRBL/ResumeJobForm.pt-BR.resx, LaserGRBL/RunFromPositionForm.pt-BR.resx, LaserGRBL/SaveOptionForm.pt-BR.resx, LaserGRBL/SettingsForm.pt-BR.resx, LaserGRBL/Strings.pt-BR.resx
PT_BR full translation revision
=> PT_BR Translation

LaserGRBL/UserControls/GrblTextBox.cs
Hello. I have CNC3018. Can I make some changes to improve work?
At first simple change. Escape button clear GRBL code text editor.
=> Grbl text box escape key

LaserGRBL/GrblFile.cs, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.Designer.cs, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.cs, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.de.resx, LaserGRBL/SvgConverter/ConvertSizeAndOptionForm.resx, LaserGRBL/SvgConverter/GCodeFromSVG.cs
Hi!
This is my very rudimentary implementation of a color filter option for the SVG import which would help at least me to be able to keep cut and engraving stuff in one SVG file.
This is the first time I code C# so tell me if I do things the "non C# way".
CU
Thomas
=> Add rudimentary color filter option for SVG import.

LaserGRBL/SvgConverter/GCodeFromSVG.cs
Filter on color attributes like stroke="green" as well.
Lower the limit because the HTML color "green" is rgb(0,128,0)!
=> Filter on color attributes like stroke="green" as well

LaserGRBL/AssemblyInfo.cs, LaserGRBL/UserControls/ImageButton.cs
=> bugfix #2254

LaserGRBL/AssemblyInfo.cs, LaserGRBL/UserControls/GrblPanel3D.cs
=> added enhanced hud with machine and laser info to opengl preview

LaserGRBL/UserControls/GrblPanel3D.cs
unit of measure in viewport bottom-left
code cleanup
=> unit of measure in viewport bottom-left

LaserGRBL/MainForm.pt-BR.resx, LaserGRBL/Strings.pt-BR.resx
Updated PT_BR translation - If  possible please give me credit on LaserGRBL web site for the portuguese translation.
Grazie Mile
Richard
=> Updated PT_BR translation

LaserGRBL/ColorScheme.cs, LaserGRBL/Core/GrblCore.cs, LaserGRBL/GrblFile.cs, LaserGRBL/MainForm.Designer.cs, LaserGRBL/MainForm.cs, LaserGRBL/MainForm.it.resx, LaserGRBL/MainForm.resx, LaserGRBL/Obj3D/Objects3D.cs, LaserGRBL/UserControls/GrblPanel3D.cs
Added:
- Bounding box rulers surrounding drawing
- New cross cursor
Fixed:
- Bug when load new picture during opengl loading
=> Bounding box rulers and new cross cursor

LaserGRBL/Firmware/FlashGrbl.pt-BR.resx, LaserGRBL/Generator/ShakeTest.pt-BR.resx, LaserGRBL/MainForm.pt-BR.resx, LaserGRBL/PSHelper/PSHelperForm.pt-BR.resx, LaserGRBL/RasterConverter/ConvertSizeAndOptionForm.pt-BR.resx, LaserGRBL/RasterConverter/RasterToLaserForm.pt-BR.resx, LaserGRBL/RunFromPositionForm.pt-BR.resx, LaserGRBL/SettingsForm.pt-BR.resx, LaserGRBL/SharpGL/SharpGL.WinForms/SceneControl.pt-BR.resx, LaserGRBL/SharpGL/SharpGL.WinForms/VertexControl.pt-BR.resx, LaserGRBL/Strings.pt-BR.resx
Updated & Revised PT_BR files for V7.12
side note: please update code on Github to V7.12, since it still has V 7.11. I opened with Visual Studio in order to test my updates, but \Generator\*.resx files are not loaded yet like in V 7.12
Grazie Mile
=> V7.12 PT_BR update
